name: Download and Release OctopusVM IMGs & ISOs from Google Drive

on:
  workflow_dispatch

jobs:
  pre_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Required Packages
      - run: sudo apt update && sudo apt install python 3 && sudo apt install python3-pip && pip install gdown
      - name: Download Windows 8
      - run: sudo apt update && sudo apt install python 3 && sudo apt install python3-pip && pip install gdown
      
